version: '3.4'

services:
  db:
    restart: always
    container_name: decide_db
    image: postgres:10.15-alpine
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - decide
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    restart: always
    container_name: decide_web
    image: decide_web:latest
    build: .
    command: ash -c "python manage.py migrate && gunicorn -w 5 decide.wsgi --timeout=500 -b 0.0.0.0:5000"
    expose:
      - "5000"
    volumes:
      - static:/app/static
    depends_on:
      - db
    networks:
      - decide
  nginx:
    restart: always
    container_name: decide_nginx
    image: decide_nginx:latest
    build:
        context: .
        dockerfile: Dockerfile-nginx
    volumes:
      - static:/app/static
    ports:
      - "8000:8000"
    depends_on:
      - web
    networks:
      - decide
    environment:
      - EMAIL_HOST_USER=projectdecidetest@gmail.com
      - EMAIL_HOST_PASSWORD=pruebadecide
      - SOCIAL_AUTH_GITHUB_KEY=01be11c9729e4d6255c4
      - SOCIAL_AUTH_GITHUB_SECRET=4a9fd81bb53d0e536abc1334c0c4ed4987ec753a
      - SOCIAL_AUTH_GOOGLE_OAUTH2_KEY=650186665562-h0k9d7pvcjdhe43iak6q6sbdikddjpkq.apps.googleusercontent.com
      - SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET=h_-Q1G_wPRz4z_6ZCsM9Z6Pu
      - SOCIAL_AUTH_FACEBOOK_KEY=587538528871702       
      - SOCIAL_AUTH_FACEBOOK_SECRET=120e5ca116b0a7659853d4e7ace9f47c

volumes:
  static:
    name: decide_static
  db:
    name: decide_db

networks:
  decide:
    driver: bridge
    ipam:
     driver: default
     config:
       - subnet: 10.5.0.0/16
